---
- hosts: 127.0.0.1
  connection: local
  become: yes
  vars:
    service_name: 'manu_service'

  vars_files: /home/secrets/prod_postgres_password
  tasks:
    - name: push image to registry
      docker_image:
        name: "{{ service_name }}"
        repository: "localhost:5000/{{ service_name }}"
        tag: "{{ lookup('env', 'BUILD_ID') }}"
        push: yes
        source: local

    - name: deploy to docker swarm (create)
      docker_swarm_service:
        name: "{{ service_name }}"
        image: "localhost:5000/{{ service_name }}:{{ lookup('env', 'BUILD_ID') }}"
        networks:
          - name: "net_prod"
        env:
          AUTH_DB_URI: "jdbc:postgresql://postgres_prod:5432/prod"
          AUTH_DB_USER: "prod"
          AUTH_DB_PSWD: "{{ prod_db_password }}"
#         todo add production args